### ISSUE TITLE
Removing person 3  different information in two files on what to remove

### ISSUE THREAD

**Issue by Diondk** [jimz011/homeassistant#12]
Hi,

first of all thank you for all the work you have done this is great and cant wait till i get it all up and running.

while trying to edit the frontpage i have seen diffrence in instructions on how to remove person 3.
 
we have the following in global_config.yaml

`Person 3 Entity Middle Photo (for best results you might want to use this, however if you don't have a third person, don't want to use this or any other reason, remove line 52 to 57 from /views/01.frontpage.yaml or replace those lines with your own card)`

we have the following in 00.frontpage.yaml
`# Person 3 (Middle Photo) if you don't need this, remove line 48 up to and including line 53!`

but actually i need to remove line 45 to 49 to get the person succesfully removed from the frontpage.

Kind Regards,
Dion

**Comment by jimz011** [comment]
You are right, the comments on the frontpage view are actually made before I created the global config. It is a remnant of my own doing (sorry for that).

I will fix this soon (I will also post new templates for the frontpage soon so that people won’t be stuck on a 3 photo frontpage).

Thank you for commenting on this!

**Comment by jimz011** [comment]
Resolved in the beta, thanks!
