### ISSUE TITLE
ha won't reload lovelace new views automaticaly . how can i solve it.

### ISSUE THREAD

**Issue by ChicBrother** [jimz011/homeassistant#2]
Hi jim, your job's amzing . Very nice .

I have a question : i clone all your config file into my ha  , everytime I modify any lovelace views files content . ha won't reload the new views automaticaly , even i click ctrl+f5 to refresh page by force it won't reload.

the solution now is to restart ha service ,but it's too trouble now .

is there any way to make ha auto reload lovelace new views ?

thx very much .

**Comment by jimz011** [comment]
Yes, you should have read the docs :P but it’s ok. To have lovelace reload whilst using includes you will have to save ui-lovelace.yaml EVERY TIME!

Do not forget this!

Even if you do not make a single change in that file you will need to save it so that lovelace knows there are changes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ChicBrother** [comment]
awesome tips , thx very much.
