### ISSUE TITLE
Idea to make code short

### ISSUE THREAD

**Issue by xMrVizzy** [jimz011/homeassistant#3]
You can change a long currently-on code with this:

```
- type: custom:decluttering-card
        template: header_text
        variables:
          - content: '##### Currently On'
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: 'custom:monster-card'
            card:
              type: glance
              columns: 3
              show_empty: true
              style: |
                ha-card {
                  border-radius: 12px;
                  background: var(--homekit-white);
                  font-size: 12px;
                  font-family: Helvetica;
                }
            filter:
              include:
                - state: 'on'
              exclude:
                - entity_id: '*tools_*'
                - entity_id: 'switch.bra_right_bedroom'
                - domain: automation
                - domain: group
          - !include ../decluttering_templates/blank-card.yaml
```

**Comment by jimz011** [comment]
Thank you, very nice addition indeed. Will be added in 0.12.0 which will be released sunday or monday. Thanks again!

**Comment by jimz011** [comment]
An addition to my thanks to you. I use the auto-entities-card instead of the monster-card. The config you sent me works perfectly fine with this card. (it has some differences to the monster-card).

Differences Auto-Entities vs Monster-Card:

 -  auto-entities has no when option. Hiding the card based on the state of an entity is better done with conditional.
 -  auto-entities supports Regular Expressions.
 -  auto-entities supports comparison operators for states as well as attributes.
 -  auto-entities can add all entities from a group
 -  auto-entities works with custom cards.

Thanks again, I have pushed this to the upcoming release of my Lovelace config. I will thank you properly in the change notes!

**Comment by xMrVizzy** [comment]
Oh cool!!
