### ISSUE TITLE
pop-up birthday card issue

### ISSUE THREAD

**Issue by jonydebu** [jimz011/homeassistant#7]
Hi , Jimmy great work , love it!! All works fine , but have an issue with the birthday pop-up card .
When i click on the birthday pop-up card to send (mail,whatsapp or phone call) , get this: 
**the template "notification_template" doesn´t exist in decluttering_templates .** 
What i´m doing wrong ? 
Thanks .

**Comment by jimz011** [comment]
It probably means you do not have the template installed. Depending on the version you run:

12.1 or below > the template must be in decluttering_templates.yaml and in the decluttering_templates folder. If you use this version you will have to copy notifications_template to your decluttering templates folder and define it in decluttering_templates.yaml

12.2 and up > the templates reside in the templates folder (you should have an include_dir in your ui-lovelace.yaml file). If you use this version the template name will be notifications instead of notifications_template. In this version there is no need to define the template in decluttering_templates.yaml

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jonydebu** [comment]
I delete the older version and reinstal the last 12.3 . In the ui-lovelace.ymal file get :
``decluttering_templates:
  !include_dir_named lovelace/templates``

I Change  ``notification_template`` to ``notification`` in ``decluterring_templates.yaml`` file too

Have the same issue :
`` The template "notification_template" doesn't exist in decluttering_templates
{
  "type": "custom:decluttering-card",
  "template": "notification_template",
  "variables": [
    {
      "icon_color": "var(--upcoming-color)"
    },
    {
      "name_color": "var(--upcoming-color)"
    },
    {
      "icon": "phone"
    },
    {
      "name": "Bel Jimmy"
    },
    {
      "card_color": "var(--homekit-card-off)"
    },
    {
      "tap_action": {
        "action": "url",
        "url": "tel://'123'",
        "haptic": "light"
      }
    }
  ]``

**Comment by jimz011** [comment]
Rename notification_template to template. Not the file but your decluttering config. And I would advise you to read up on the docs of how to use the decluttering card and templates.

Find the docs here:
https://github.com/custom-cards/decluttering-card

The template defined in decluttering config (and almost every button/card in my config is a decluttering card) must be the same as the template name.

So your config should look like:
```
- type: custom:decluttering-card
 template: notification
 variables:
    - variables here
```

I hope this helps. Jimz

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jonydebu** [comment]
That´s it Jimmy , works fine now. Thanks for your help . Repeat GREAT , GREAT , GREAT WORK !!!
Close this issue now.
